# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  name: 'Default'

steps: 
- script: |
    pwd
    ls -al
    ./gradlew clean build bootBuildImage -x test 
  displayName: 'Build the tanzu bank services'

